### ISSUE TITLE
[ASAP] Weird error in coverage

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/swmp#127]
Check out the [branch](https://github.com/mick-warehime/swmp/tree/issue-123-backpack-bug) I was working on to fix #123. I fixed the bug and added a test that failed on that bug prior to the fix, using a new unittest module test_dungeon_controller.py. I can run individual unittests in pycharm and all of them will pass. But when I run the coverage -m ... command, test_controller.py fails. If I delete test_dungeon_controller.py (or move it outside the src/ folder), then for some reason test_controller.py suddenly passes. Do you have any idea why this is happening?  

I will fix the other issue you mention in #123 (modules moving around in backpack) after this is done.

**Comment by mick-warehime** [comment]
one thing i've noticed is if you init a dungeon controller in multiple tests then one will fail - is this what you are seeing?

**Comment by mick-warehime** [comment]
for now you can keep all the tests in one controller test file and make your checkin so you are not blocked with your current change. then we can solve this issue

**Comment by dvirk** [comment]
In #136 I renamed the new test so it runs first, then manually uninitialized the initialized classes. That's the best fix I could come up with.
