### ISSUE TITLE
[med] Why are there two builds when you generate a PR?

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/swmp#182]
It seems like the two builds are doing the same thing... What is the difference?
![screen shot 2017-12-31 at 4 36 05 pm](https://user-images.githubusercontent.com/8898439/34464879-d370e79a-ee48-11e7-894c-195cfac46fed.png)

**Comment by mick-warehime** [comment]
![image](https://user-images.githubusercontent.com/986174/34469036-db43ff7a-eeca-11e7-9b32-1f97989ec27a.png)

the pr contains a merge the pull is just in your branch

**Comment by dvirk** [comment]
Oh.
