### ISSUE TITLE
hit rects should be centered

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/swmp#28]
repro: press 'h' while playing and find a mob. the hit rects are aligned to top left

**Comment by dvirk** [comment]
This only seems to be happening when the Mobs are moving diagonally. I think it is because the center of the image is not the Mob's head, so when the image is rotated the head moves around the center point.

**Comment by dvirk** [comment]
My next pull request should fix this.

**Comment by dvirk** [comment]
Oops I made more changes to the branch before I merged with master. I'll start using better branch names. Now the issue is fixed though.
